"""Artifact models for structured agent-generated content."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum


class ArtifactType(StrEnum):
    """Categorized type of a structured artifact generated by the agent."""

    WALKTHROUGH = "walkthrough"
    IMPLEMENTATION_PLAN = "implementation_plan"
    CODE_REVIEW = "code_review"
    DOCUMENT = "document"
    OTHER = "other"


@dataclass
class Artifact:
    """A structured artifact generated during an agent session."""

    id: str
    title: str
    summary: str = ""
    content: str = ""
    artifact_type: ArtifactType = ArtifactType.OTHER
    file_paths: list[str] = field(default_factory=list)
    created_at: str = field(default_factory=lambda: datetime.now(UTC).strftime("%H:%M"))
