"""Data models for conversation messages, execution steps, and background tasks."""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any


class StepType(StrEnum):
    """Categorized type of an intermediate agent execution step."""

    WORKED = "worked"
    FILES = "files"
    COMMANDS = "commands"


class TaskStatus(StrEnum):
    """Lifecycle status of a background task tracked by the inspector."""

    RUNNING = "running"
    COMPLETE = "complete"
    ERROR = "error"


@dataclass
class BackgroundTask:
    """A long-running background task (spell or subagent) tracked in state."""

    id: str
    name: str
    status: TaskStatus = TaskStatus.RUNNING
    progress: float = 0.0
    parent_id: str | None = None
    started_at: float = field(default_factory=time.monotonic)
    ended_at: float | None = None
    result: str = ""
    error: str | None = None


@dataclass
class SkillInfo:
    """Summary of a discovered Skill rendered in the context inspector."""

    name: str
    description: str = ""
    scope: str = ""
    path: str = ""
    invoked: bool = False


@dataclass
class CommandExecution:
    """Execution details of a shell command invocation."""

    command: str
    output: str = ""
    exit_code: int = 0
    is_error: bool = False
    duration_seconds: float = 0.0


@dataclass
class FileExploration:
    """Exploration details of a file or directory operation."""

    path: str
    operation: str = "read"
    lines: str | None = None
    details: str | None = None
    is_error: bool = False


@dataclass
class ExecutionStep:
    """A collapsible execution card grouping internal operations."""

    step_type: StepType
    title: str = ""
    duration_seconds: float = 0.0
    commands: list[CommandExecution] = field(default_factory=list)
    files: list[FileExploration] = field(default_factory=list)
    details: list[str] = field(default_factory=list)
    is_complete: bool = False
    spell_name: str = ""
    result: str = ""
    params: dict[str, Any] = field(default_factory=dict)


@dataclass
class DiffLine:
    """A single line within a diff hunk with type and line number context."""

    content: str
    line_type: str = "context"
    old_line_number: int | None = None
    new_line_number: int | None = None


@dataclass
class DiffHunk:
    """A contiguous block of changes within a unified diff."""

    source_start: int = 0
    source_length: int = 0
    target_start: int = 0
    target_length: int = 0
    lines: list[DiffLine] = field(default_factory=list)


@dataclass
class DiffView:
    """Parsed diff representation for a single file."""

    file_path: str
    status: str = "modified"
    hunks: list[DiffHunk] = field(default_factory=list)
    additions: int = 0
    deletions: int = 0


@dataclass
class ChangedFile:
    """Summary of a changed file with addition/deletion counts."""

    path: str
    status: str = "modified"
    additions: int = 0
    deletions: int = 0


class ArtifactType(StrEnum):
    """Categorized type of a structured artifact generated by the agent."""

    WALKTHROUGH = "walkthrough"
    IMPLEMENTATION_PLAN = "implementation_plan"
    CODE_REVIEW = "code_review"
    DOCUMENT = "document"
    OTHER = "other"


@dataclass
class Artifact:
    """A structured artifact generated during an agent session."""

    id: str
    title: str
    summary: str = ""
    content: str = ""
    artifact_type: ArtifactType = ArtifactType.OTHER
    file_paths: list[str] = field(default_factory=list)
    created_at: str = field(default_factory=lambda: datetime.now(UTC).strftime("%H:%M"))


class MessagePartType(StrEnum):
    """Categorized type of a content block in an assistant message."""

    CONTEMPLATION = "contemplation"
    STEP = "step"
    TEXT = "text"
    ARTIFACT = "artifact"


@dataclass
class MessagePart:
    """A single sequential content block in an assistant message."""

    part_type: MessagePartType
    text: str = ""
    step: ExecutionStep | None = None
    artifact: Artifact | None = None


@dataclass
class ChatMessage:
    """A single chat message in the conversation thread.

    ``parts`` is authoritative; ``content``, ``contemplation``, and ``steps``
    are projections assembled by InvocationTranscript.
    """

    role: str
    timestamp: str = field(default_factory=lambda: datetime.now(UTC).strftime("%H:%M"))
    model: str | None = None
    mana_used: int = 0
    is_streaming: bool = False
    timeline: list[dict[str, Any]] = field(default_factory=list)
    feedback: str | None = None
    is_error: bool = False
    error_message: str | None = None
    attachments: list[str] = field(default_factory=list)
    artifacts: list[Artifact] = field(default_factory=list)
    parts: list[MessagePart] = field(default_factory=list)

    @property
    def content(self) -> str:
        """Plain-text projection of the TEXT parts."""
        return "".join(
            p.text for p in self.parts if p.part_type is MessagePartType.TEXT
        )

    @property
    def contemplation(self) -> list[str]:
        """Contemplation projection: texts of the CONTEMPLATION parts."""
        return [
            p.text for p in self.parts if p.part_type is MessagePartType.CONTEMPLATION
        ]

    @property
    def steps(self) -> list[ExecutionStep]:
        """Execution-step projection: steps carried by STEP parts."""
        return [
            p.step
            for p in self.parts
            if p.part_type is MessagePartType.STEP and p.step is not None
        ]
