"""Data models for conversation messages, execution steps, and background tasks."""

from __future__ import annotations

import re
import time
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any


class StepType(StrEnum):
    """Categorized type of an intermediate agent execution step."""

    WORKED = "worked"
    FILES = "files"
    COMMANDS = "commands"


class TaskStatus(StrEnum):
    """Lifecycle status of a background task tracked by the inspector."""

    RUNNING = "running"
    COMPLETE = "complete"
    ERROR = "error"


@dataclass
class BackgroundTask:
    """A long-running background task (spell or subagent) tracked in state."""

    id: str
    name: str
    status: TaskStatus = TaskStatus.RUNNING
    progress: float = 0.0
    parent_id: str | None = None
    started_at: float = field(default_factory=time.monotonic)
    ended_at: float | None = None
    result: str = ""
    error: str | None = None


@dataclass
class SkillInfo:
    """Summary of a discovered Skill rendered in the context inspector."""

    name: str
    description: str = ""
    scope: str = ""
    path: str = ""
    invoked: bool = False


@dataclass
class CommandExecution:
    """Execution details of a shell command invocation."""

    command: str
    output: str = ""
    exit_code: int = 0
    is_error: bool = False
    duration_seconds: float = 0.0


@dataclass
class FileExploration:
    """Exploration details of a file or directory operation."""

    path: str
    operation: str = "read"
    lines: str | None = None
    details: str | None = None
    is_error: bool = False


@dataclass
class ExecutionStep:
    """A collapsible execution card grouping internal operations."""

    step_type: StepType
    title: str = ""
    duration_seconds: float = 0.0
    commands: list[CommandExecution] = field(default_factory=list)
    files: list[FileExploration] = field(default_factory=list)
    details: list[str] = field(default_factory=list)
    is_complete: bool = False
    spell_name: str = ""
    result: str = ""
    params: dict[str, Any] = field(default_factory=dict)


@dataclass
class DiffLine:
    """A single line within a diff hunk with type and line number context."""

    content: str
    line_type: str = "context"
    old_line_number: int | None = None
    new_line_number: int | None = None


@dataclass
class DiffHunk:
    """A contiguous block of changes within a unified diff."""

    source_start: int = 0
    source_length: int = 0
    target_start: int = 0
    target_length: int = 0
    lines: list[DiffLine] = field(default_factory=list)


@dataclass
class DiffView:
    """Parsed diff representation for a single file."""

    file_path: str
    status: str = "modified"
    hunks: list[DiffHunk] = field(default_factory=list)
    additions: int = 0
    deletions: int = 0


@dataclass
class ChangedFile:
    """Summary of a changed file with addition/deletion counts."""

    path: str
    status: str = "modified"
    additions: int = 0
    deletions: int = 0


class ArtifactType(StrEnum):
    """Categorized type of a structured artifact generated by the agent."""

    WALKTHROUGH = "walkthrough"
    IMPLEMENTATION_PLAN = "implementation_plan"
    CODE_REVIEW = "code_review"
    DOCUMENT = "document"
    OTHER = "other"


@dataclass
class Artifact:
    """A structured artifact generated during an agent session."""

    id: str
    title: str
    summary: str = ""
    content: str = ""
    artifact_type: ArtifactType = ArtifactType.OTHER
    file_paths: list[str] = field(default_factory=list)
    created_at: str = field(default_factory=lambda: datetime.now(UTC).strftime("%H:%M"))


class MessagePartType(StrEnum):
    """Categorized type of a content block in an assistant message."""

    CONTEMPLATION = "contemplation"
    STEP = "step"
    TEXT = "text"
    ARTIFACT = "artifact"


@dataclass
class MessagePart:
    """A single sequential content block in an assistant message."""

    part_type: MessagePartType
    text: str = ""
    step: ExecutionStep | None = None
    artifact: Artifact | None = None


@dataclass
class ChatMessage:
    """A single chat message in the conversation thread."""

    role: str
    content: str = ""
    contemplation: list[str] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.now(UTC).strftime("%H:%M"))
    model: str | None = None
    mana_used: int = 0
    is_streaming: bool = False
    steps: list[ExecutionStep] = field(default_factory=list)
    parts: list[MessagePart] = field(default_factory=list)
    timeline: list[dict[str, Any]] = field(default_factory=list)
    feedback: str | None = None
    is_error: bool = False
    error_message: str | None = None
    attachments: list[str] = field(default_factory=list)
    artifacts: list[Artifact] = field(default_factory=list)

    def get_parts(self) -> list[MessagePart]:
        """Return sequential parts, synthesizing from fields if parts is empty."""
        if self.parts:
            return self.parts
        synthetic: list[MessagePart] = []
        for c in self.contemplation:
            synthetic.append(
                MessagePart(part_type=MessagePartType.CONTEMPLATION, text=c)
            )
        for s in self.steps:
            synthetic.append(MessagePart(part_type=MessagePartType.STEP, step=s))
        if self.content:
            synthetic.append(
                MessagePart(part_type=MessagePartType.TEXT, text=self.content)
            )
        for a in self.artifacts:
            synthetic.append(
                MessagePart(part_type=MessagePartType.ARTIFACT, artifact=a)
            )
        return synthetic


def extract_contemplation_tags(text: str) -> tuple[str, list[str]]:
    """Extract <think>...</think> or <thought>...</thought> tags from text.

    Returns (cleaned_content, extracted_contemplation_list).
    """
    if not text:
        return "", []

    pattern = re.compile(
        r"<(?:think|thought)>(.*?)</(?:think|thought)>",
        re.DOTALL | re.IGNORECASE,
    )
    thoughts: list[str] = []

    def _replace(m: re.Match[str]) -> str:
        thoughts.append(m.group(1).strip())
        return ""

    cleaned = pattern.sub(_replace, text)

    # Check for unclosed <think> or <thought> tag at end of streaming buffer
    unclosed = re.compile(
        r"<(?:think|thought)>(.*)$",
        re.DOTALL | re.IGNORECASE,
    )
    unclosed_match = unclosed.search(cleaned)
    if unclosed_match:
        thoughts.append(unclosed_match.group(1).strip())
        cleaned = unclosed.sub("", cleaned)

    extracted_thoughts = [t for t in thoughts if t]
    return cleaned.strip(), extracted_thoughts


def extract_ordered_content(text: str) -> list[dict[str, str]]:
    """Extract text and contemplation segments in original chronological order.

    Returns list of {"type": "text"|"thought", "text": str} entries.
    """
    if not text:
        return []

    pattern = re.compile(
        r"<(?:think|thought)>(.*?)</(?:think|thought)>",
        re.DOTALL | re.IGNORECASE,
    )
    parts: list[dict[str, str]] = []
    last_end = 0

    for match in pattern.finditer(text):
        if match.start() > last_end:
            text_segment = text[last_end : match.start()].strip()
            if text_segment:
                parts.append({"type": "text", "text": text_segment})
        thought_text = match.group(1).strip()
        if thought_text:
            parts.append({"type": "thought", "text": thought_text})
        last_end = match.end()

    if last_end < len(text):
        text_segment = text[last_end:].strip()
        if text_segment:
            parts.append({"type": "text", "text": text_segment})

    return parts
